\documentclass{article}
\usepackage[margin=0.5in]{geometry}

\usepackage{multirow}
\usepackage[table,xcdraw]{xcolor}
\usepackage{makecell}
\usepackage{float}

\begin{document}


<<echo=FALSE>>=
library(Hmisc)
library(dplyr)

MAPfreeze.list <- readRDS("/Users/khanoa/box/VMAC BIOSTAT/DATA/MAP/rawData/MAPfreeze_20201201.rds")

map_id <- input$map_id
epoch <- input$epoch

options(digits=2)
@

<<echo = FALSE, results="hide", message=FALSE>>=
if (epoch == 1) {
  data <- MAPfreeze.list$epoch_1$data$main
} else if (epoch == 2) {
  data <- MAPfreeze.list$epoch_2$data$main
} else if (epoch == 3) {
  data <- MAPfreeze.list$epoch_3$data$main
} else if (epoch == 4) {
  data <- MAPfreeze.list$epoch_4$data$main
} else if (epoch == 5) {
  data <- MAPfreeze.list$epoch_5$data$main
}

np.var <- Hmisc::Cs(
  map_id,
  vmac_id,
  age,
  education,
  np_date,
  np_examiner,
  ethnicity,
  race,
  sex,
  np_notes,
  np_moca,
  np_cvlt1,
  np_cvlt2,
  np_cvlt3,
  np_cvlt4,
  np_cvlt5,
  np_cvlt1z,
  np_cvlt2z,
  np_cvlt3z,
  np_cvlt4z,
  np_cvlt5z,
  np_cvlt1to5,
  np_cvlt1to5_tscore,
  np_cvltb,
  np_cvlt_sdfr,
  np_cvlt_sdcr,
  np_cvlt_ldfr,
  np_cvlt_ldcr,
  np_cvltrec_hits,
  np_cvltrec_falsepos,
  np_cvlt_reps,
  np_cvlt_intrus,
  np_cvltbz,
  np_cvlt_sdfr_z,
  np_cvlt_sdcr_z,
  np_cvlt_ldfr_z,
  np_cvlt_ldcr_z,
  np_cvltrec_hits_z,
  np_cvltrecog_falsepos_z,
  np_cvlt_reps_z,
  np_cvlt_intrus_z,
  np_biber1,
  np_biber2,
  np_biber3,
  np_biber4,
  np_biber5,
  np_biberb,
  np_biber_sd,
  np_biber_ld,
  np_biber_hits,
  np_biber_falsealarms,
  np_biber_t1to5_persev,
  np_biber_t1to5_extra,
  np_bnt,
  np_anim_tscore,
  np_hvot,
  np_tmta,
  np_tmta_seqerr,
  np_tmta_seterr,
  np_tmtb,
  np_tmtb_seqerr,
  np_tmtb_seterr,
  np_color,
  np_word,
  np_inhibit,
  np_fas_f,
  np_fas_a,
  np_fas_s,
  np_fas_tscore,
  np_fas_intrus,
  np_fas_rep,
  np_tower_ruleviol,
  np_digsymb,
  np_mc1_time,
  np_mc2_time,
  np_mc3_time,
  np_mc4_time,
  np_mc5_time,
  np_mc6_time,
  np_mc7_time,
  np_mc8_time,
  np_mc1_omissions,
  np_mc2_omissions,
  np_mc3_omissions,
  np_mc4_omissions,
  np_mc5_omissions,
  np_mc6_omissions,
  np_mc7_omissions,
  np_mc8_omissions,
  np_mc1_falsepos,
  np_mc2_falsepos,
  np_mc3_falsepos,
  np_mc4_falsepos,
  np_mc5_falsepos,
  np_mc6_falsepos,
  np_mc7_falsepos,
  np_mc8_falsepos,
  np_mc_kaplan,
  np_mc_kaplan_ss,
  np_symbol,
  np_symbol_trials
)

np.var <- c(
  np.var,
  paste0("np_anim_q", formatC(1:4, width = 1, flag = "0")),
  c(paste0("gds", formatC(1:9, width = 1)), paste0("gds", formatC(10:30, width = 2, flag = "0"))),
  paste0("np_tower", formatC(1:9, width = 2, flag = "0"))
)

np_tower.var <- paste0("np_tower", formatC(1:9, width = 2, flag = "0"))

data <- data[data$map_id == map_id, np.var]

# np_anim.var <- paste0("np_anim_q", formatC(1:4, width = 1, flag = "0"))
# np_gds.var <- c(paste0("gds", formatC(1:9, width = 1)), paste0("gds", formatC(10:30, width = 2, flag = "0")))

data <- within(data, {
  np_age <- age
  np_education <- education
  
  if (!np_age %in% 60:110) {
    stop("Age is out of bounds.")
  }
  
  if (!np_education %in% 0:22) {
    stop("Education is out of bounds.")
  }
  
  # Global Cognition
  
  ## MOCA
  
  np_moca.interpretation <- case_when(
    np_moca < 0 ~ "ERROR",
    np_moca < 23 ~ "Impaired",
    np_moca < 27 ~ "Borderline",
    np_moca < 31 ~ "Normal",
    TRUE ~ "ERROR"
  )
  
  # Learning & Memory
  
  ## CVLT-II
  
  #! Manual coding of scaled scores
  
  ## Biber
  
  np_biber1.scaled <- (np_biber1 - 13.7) / 5.9
  np_biber2.scaled <- (np_biber2 - 20.4) / 7.4
  np_biber3.scaled <- (np_biber3 - 24.5) / 7
  np_biber4.scaled <- (np_biber4 - 26.7) / 8.4
  np_biber5.scaled <- (np_biber5 - 29.6) / 6.8
  
  np_biber_t1to5 <- sum(c(np_biber1, np_biber2, np_biber3, np_biber4, np_biber5))
  np_biber_t1to5.scaled <- (np_biber_t1to5 - 114.5) / 34.7
  
  np_biberb.scaled <- (np_biberb - 8.5) / 5
  np_biber_sd.scaled <- (np_biber_sd - 26.4) / 7
  np_biber_ld.scaled <- (np_biber_ld - 28) / 7
  
  # Language
  
  ## BNT-30 item (even)
  
  np_bnt.scaled <- (np_bnt - 26) / 3.4
  
  ## Animals
  
  np_anim <- sum(np_anim_q1, np_anim_q2, np_anim_q3, np_anim_q4)
  
  #! Manual coding of scaled scores
  
  # Mood
  
  ## GDS
  
  np_gds <- sum(gds1, gds2, gds3, gds4, gds5, gds6, gds7, gds8, gds9, gds10, gds11, gds12, gds13, gds14, gds15, gds16, gds17, gds18, gds19, gds20, gds21, gds22, gds23, gds24, gds25, gds26, gds27, gds28, gds29, gds30)
  
  np_gds.interpretation <- case_when(
    np_gds < 0 ~ "ERROR",
    np_gds < 10 ~ "Normal",
    np_gds < 20 ~ "Mildly Depressed",
    np_gds < 31 ~ "Severely Depressed",
    TRUE ~ "ERROR"
  )
  
  # Visuospatial Skills
  
  ## HVOT
  
  np_hvot.age <- case_when(
    np_age >= 60 & np_age <= 64 ~ "60-64",
    np_age >= 65 & np_age <= 110 ~ "65-110",
    TRUE ~ "ERROR"
  )
  
  np_hvot.raw <- ifelse(np_hvot > max(np_hvot.lookup$raw), max(np_hvot.lookup$raw), np_hvot) %>%
    floor()
  
  np_hvot.scaled <- np_hvot.lookup %>%
    filter(age == np_hvot.age & education == np_education & raw == np_hvot.raw) %>%
    pull(scaled)
  
  # Attention/Executive Functioning/Information Processing
  
  ## DKEFS: Trail Making Test
  
  np_tmta.raw <- ifelse(np_tmta > max(np_tmta.lookup$raw), max(np_tmta.lookup$raw), np_tmta)
  np_tmta.scaled <- np_tmta.lookup %>%
    filter(age == np_age & raw == np_tmta.raw) %>%
    pull(scaled)
  
  np_tmta_seqerr.raw <- ifelse(np_tmta_seqerr > max(np_tmta_seqerr.lookup$raw), max(np_tmta_seqerr.lookup$raw), np_tmta_seqerr)
  np_tmta_seqerr.scaled <- np_tmta_seqerr.lookup %>%
    filter(age == np_age & raw == np_tmta_seqerr.raw) %>%
    pull(scaled)
  
  np_tmta_seterr.scaled <- np_tmta_seterr.lookup %>%
    filter(age == np_age & raw == np_tmta_seterr) %>%
    pull(scaled)
  
  np_tmtb.scaled <- np_tmtb.lookup %>%
    filter(age == np_age & raw == np_tmtb) %>%
    pull(scaled)
  
  np_tmtb_seqerr.scaled <- np_tmtb_seqerr.lookup %>%
    filter(age == np_age & raw == np_tmtb_seqerr) %>%
    pull(scaled)
  
  np_tmtb_seterr.scaled <- np_tmtb_seterr.lookup %>%
    filter(age == np_age & raw == np_tmtb_seterr) %>%
    pull(scaled)
  
  
  ## DKEFS: Color-Word
  
  np_color.scaled <- np_color.lookup %>%
    filter(age == np_age & raw == np_color) %>%
    pull(scaled)
  
  np_word.scaled <- np_word.lookup %>%
    filter(age == np_age & raw == np_word) %>%
    pull(scaled)
  
  np_inhibit.scaled <- np_inhibit.lookup %>%
    filter(age == np_age & raw == np_inhibit) %>%
    pull(scaled)
  
  ## COWA
  
  np_fas <- sum(c(np_fas_f, np_fas_a, np_fas_s))
  
  ## Tower Test
  
  np_tower <- sum(np_tower01, np_tower02, np_tower03, np_tower04, np_tower05, np_tower06, np_tower07, np_tower08, np_tower09)
  
  np_tower.scaled <- np_tower.lookup %>%
    filter(age == np_age & raw == np_tower) %>%
    pull(scaled)
  
  np_tower_ruleviol.scaled <- np_tower_ruleviol.lookup %>%
    filter(age == np_age & raw == np_tower_ruleviol) %>%
    pull(scaled)
  
  ## Digit Symbol Coding
  
  np_digsymb.scaled <- np_digsymb.lookup %>%
    filter(age == np_age & raw == np_digsymb) %>%
    pull(scaled)
  
  # Mental Control
  
  np_mc1.accuracy.index <- 1 - (np_mc1_omissions + np_mc1_falsepos) / 20
  np_mc2.accuracy.index <- 1 - (np_mc2_omissions + np_mc2_falsepos) / 26
  np_mc3.accuracy.index <- 1 - (np_mc3_omissions + np_mc3_falsepos) / 14
  
  np_mc1_3.total <- sum(c(np_mc1.accuracy.index, np_mc2.accuracy.index, np_mc3.accuracy.index))
  
  np_mc4.accuracy.index <- 1 - (np_mc4_omissions + np_mc4_falsepos) / 12
  np_mc5.accuracy.index <- 1 - (np_mc5_omissions + np_mc5_falsepos) / 12
  np_mc6.accuracy.index <- 1 - (np_mc6_omissions + np_mc6_falsepos) / 9
  np_mc7.accuracy.index <- 1 - (np_mc7_omissions + np_mc7_falsepos) / 11
  np_mc8.accuracy.index <- 1 - (np_mc8_omissions + np_mc8_falsepos) / 13
  
  np_mc_auto_mc.accuracy.index <- mean(c(np_mc1.accuracy.index, np_mc2.accuracy.index, np_mc3.accuracy.index, np_mc4.accuracy.index), na.rm = FALSE)
  
  #! this formula does not align with what is in rVMAP::derive_pvlt()
  np_mc_nonauto_mc.accuracy.index <- mean(c(np_mc5.accuracy.index, np_mc6.accuracy.index, np_mc7.accuracy.index, np_mc8.accuracy.index), na.rm = FALSE)
  
  # WMS-IV Symbol Span
  
  np_symbol.scaled <- np_symbol.lookup %>%
    filter(age == np_age & raw == np_symbol) %>%
    pull(scaled)
  
})

attach(data)
@

\noindent VMAP \#: \Sexpr{vmac_id} \\
Age: \Sexpr{age} \\
Testing Date: \Sexpr{np_date} \\

\begin{table}[!ht]

\centering

\begin{tabular}{ccc}
\hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{Global Cognition}}            \\ \hline
\rowcolor[HTML]{C0C0C0} 
\textbf{MOCA}                   & Raw Score    & Interpretation                  \\
Total                           & \Sexpr{np_moca}        & \Sexpr{np_moca.interpretation}                           \\ \hline
                                &              &                                 \\ \hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{Learning \& Memory}}          \\ \hline
\rowcolor[HTML]{C0C0C0} 
\textbf{CVLT-II}                & Raw Score    & Z-Score                         \\
Trial 1                         & \Sexpr{np_cvlt1}        & \Sexpr{np_cvlt1z}                           \\
Trial 2                         & \Sexpr{np_cvlt2}        & \Sexpr{np_cvlt2z}                           \\
Trial 3                         & \Sexpr{np_cvlt3}        & \Sexpr{np_cvlt3z}                           \\
Trial 4                         & \Sexpr{np_cvlt4}        & \Sexpr{np_cvlt4z}                           \\
Trial 5                         & \Sexpr{np_cvlt5}        & \Sexpr{np_cvlt5z}                           \\
                                &              & \cellcolor[HTML]{C0C0C0}T-Score \\
Total T1-T5                     & \Sexpr{np_cvlt1to5}        & \Sexpr{np_cvlt1to5_tscore}                           \\
List B                          & \Sexpr{np_cvltb}        & \Sexpr{np_cvltbz}                           \\
Short Delay Free Recall         & \Sexpr{np_cvlt_sdfr}        & \Sexpr{np_cvlt_sdfr_z}                           \\
Short Delay Cued Recall         & \Sexpr{np_cvlt_sdcr}        & \Sexpr{np_cvlt_sdcr_z}                           \\
Long Delay Free Recall          & \Sexpr{np_cvlt_ldfr}        & \Sexpr{np_cvlt_ldfr_z}                           \\
Long Delay Cued Recall          & \Sexpr{np_cvlt_ldcr}        & \Sexpr{np_cvlt_ldcr_z}                           \\
Total Recognition Hits          & \Sexpr{np_cvltrec_hits}        & \Sexpr{np_cvltrec_hits_z}                           \\
Total False Positives           & \Sexpr{np_cvltrec_falsepos}        & \Sexpr{np_cvltrecog_falsepos_z}                           \\
Total Repetitions               & \Sexpr{np_cvlt_reps}        & \Sexpr{np_cvlt_reps_z}                           \\
Total Intrusions                & \Sexpr{np_cvlt_intrus}        & \Sexpr{np_cvlt_intrus_z}                           \\ \hline

\rowcolor[HTML]{C0C0C0} 
\textbf{Biber}                  & Raw Score    & Z-Score                         \\
Trial 1                         & \Sexpr{np_biber1}        & \Sexpr{np_biber1.scaled}                           \\
Trial 2                         & \Sexpr{np_biber2}        & \Sexpr{np_biber2.scaled}                           \\
Trial 3                         & \Sexpr{np_biber3}        & \Sexpr{np_biber3.scaled}                           \\
Trial 4                         & \Sexpr{np_biber4}        & \Sexpr{np_biber4.scaled}                           \\
Trial 5                         & \Sexpr{np_biber5}        & \Sexpr{np_biber5.scaled}                           \\
Total T1-T5                     & \Sexpr{np_biber_t1to5}        & \Sexpr{np_biber_t1to5.scaled}                           \\
Distractor Set                  & \Sexpr{np_biberb}        & \Sexpr{np_biberb.scaled}                           \\
Immediate Recall                & \Sexpr{np_biber_sd}        & \Sexpr{np_biber_sd.scaled}                           \\
Delayed Recall                  & \Sexpr{np_biber_ld}        & \Sexpr{np_biber_ld.scaled}                           \\
Recognition - Hits              & \Sexpr{np_biber_hits}        & \cellcolor[HTML]{C0C0C0}        \\
Recognition - Total False Alarm & \Sexpr{np_biber_falsealarms}        & \cellcolor[HTML]{C0C0C0}        \\
Total Preservations             & \Sexpr{np_biber_t1to5_persev}        & \cellcolor[HTML]{C0C0C0}        \\
Total Extraneous Responses      & \Sexpr{np_biber_t1to5_extra}        & \cellcolor[HTML]{C0C0C0}        \\ \hline
                                &              &                                 \\ \hline

\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{Language}}                        \\ \hline
\rowcolor[HTML]{C0C0C0} 
\textbf{BNT-30 item (even)}     & Raw Score    & Z-Score                  \\
Total                           & \Sexpr{np_bnt}        & \Sexpr{np_bnt.scaled}                \\ \hline
\rowcolor[HTML]{C0C0C0} 
\textbf{Animals}     & Raw Score    & T-Score                  \\
Total                           & \Sexpr{np_anim}        & \Sexpr{np_anim_tscore}                \\ \hline
                                &              &                                 \\ \hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{Mood}}                        \\ \hline
\rowcolor[HTML]{C0C0C0} 
\textbf{GDS}                    & Raw Score    & Interpretation                  \\
Total                           & \Sexpr{np_gds}        & \Sexpr{np_gds.interpretation}                           \\ \hline
\end{tabular}
\end{table}

% \end{minipage}

% \begin{minipage}{0.45\textwidth}
\begin{table}[!ht]

\centering

\begin{tabular}{ccccc}
\hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{5}{c}{\cellcolor[HTML]{C0C0C0}\textbf{Visuospatial Skills}}                                                    \\ \hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{HVOT}}                     & Raw Score        & T-Score                  \\
\multicolumn{3}{c}{Total}                                                     & \Sexpr{np_hvot}            & \Sexpr{np_hvot.scaled}                    \\ \hline
                          &                        &                          &                  &                          \\ \hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{5}{c}{\cellcolor[HTML]{C0C0C0}\textbf{Attention/Executive Functioning/Information Processing}}                 \\ \hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{DKEFS: Trail Making Test}} & Raw Score        & Scaled Score/Percentile  \\
\multicolumn{3}{c}{Number Sequencing: Time}                                   & \Sexpr{np_tmta}            & \Sexpr{np_tmta.scaled}                    \\
\multicolumn{3}{c}{Number Sequencing: Errors (\%)}                  & \Sexpr{np_tmta_seqerr}            & \Sexpr{np_tmta_seqerr.scaled}                    \\
\multicolumn{3}{c}{N: Set-Loss Errors (\%)}                         & \Sexpr{np_tmta_seterr}            & \Sexpr{np_tmta_seterr.scaled}                    \\
\multicolumn{3}{c}{Number-Letter: Time}                                       & \Sexpr{np_tmtb}            & \Sexpr{np_tmtb.scaled}                    \\
\multicolumn{3}{c}{N-L: Sequencing Errors (\%)}                               & \Sexpr{np_tmtb_seqerr}            & \Sexpr{np_tmtb_seqerr.scaled}                    \\
\multicolumn{3}{c}{N-L: Set-Loss Errors (\%)}                                 & \Sexpr{np_tmtb_seterr}            & \Sexpr{np_tmtb_seterr.scaled}                    \\ \hline

\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{DKEFS: Color-Word}}        & Raw Score        & Scaled Score  \\
\multicolumn{3}{c}{Color Naming Time}                                         & \Sexpr{np_color}            & \Sexpr{np_color.scaled}                    \\
\multicolumn{3}{c}{Word Naming Time}                                          & \Sexpr{np_word}            & \Sexpr{np_word.scaled}                    \\
\multicolumn{3}{c}{Inhibition Time}                                           & \Sexpr{np_inhibit}            & \Sexpr{np_inhibit.scaled}                    \\ \hline

\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}\textbf{COWA}}                     & Raw Score        & T-Score                  \\
\multicolumn{3}{c}{F - Total Words}                                           & \Sexpr{np_fas_f}            & \cellcolor[HTML]{C0C0C0} \\
\multicolumn{3}{c}{A - Total Words}                                           & \Sexpr{np_fas_a}            & \cellcolor[HTML]{C0C0C0} \\
\multicolumn{3}{c}{S - Total Words}                                           & \Sexpr{np_fas_s}            & \cellcolor[HTML]{C0C0C0} \\
\multicolumn{3}{c}{Total FAS Words}                                           & \Sexpr{np_fas}            & \Sexpr{np_fas_tscore}                    \\
\multicolumn{3}{c}{Total Intrusions}                                          & \Sexpr{np_fas_intrus}            & \cellcolor[HTML]{C0C0C0} \\
\multicolumn{3}{c}{Total Repititions}                                         & \Sexpr{np_fas_rep}            & \cellcolor[HTML]{C0C0C0} \\ \hline

\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\textbf{Tower Test}}                                       & Raw Score        & Scaled Score/Percentile  \\
\multicolumn{3}{c}{Achievement Score}                                         & \Sexpr{np_tower}            & \Sexpr{np_tower.scaled}                    \\
\multicolumn{3}{c}{Total Rule Violations (\%)}                                & \Sexpr{np_tower_ruleviol}            & \Sexpr{np_tower_ruleviol.scaled}                    \\ \hline

\rowcolor[HTML]{C0C0C0} 
\multicolumn{5}{c}{\cellcolor[HTML]{C0C0C0}\textbf{Mental Control}}                                                         \\ \hline
\rowcolor[HTML]{C0C0C0} 
Item                      & Time                   & Omissions                & False Positives  & Accuracy Index           \\
Item 1                    & \Sexpr{np_mc1_time}                  & \Sexpr{np_mc1_omissions}                    & \Sexpr{np_mc1_falsepos}            & \Sexpr{np_mc1.accuracy.index}                    \\
Item 2                    & \Sexpr{np_mc2_time}                  & \Sexpr{np_mc2_omissions}                    & \Sexpr{np_mc2_falsepos}            & \Sexpr{np_mc2.accuracy.index}                    \\
Item 3                    & \Sexpr{np_mc3_time}                  & \Sexpr{np_mc3_omissions}                    & \Sexpr{np_mc3_falsepos}            & \Sexpr{np_mc3.accuracy.index}                    \\
\multicolumn{4}{r}{\textit{Item 1-3 Total Score}}                                                & \Sexpr{np_mc1_3.total}                    \\
Item 4                    & \Sexpr{np_mc4_time}                  & \Sexpr{np_mc4_omissions}                    & \Sexpr{np_mc4_falsepos}            & \Sexpr{np_mc4.accuracy.index}                    \\
Item 5                    & \Sexpr{np_mc5_time}                  & \Sexpr{np_mc5_omissions}                    & \Sexpr{np_mc5_falsepos}            & \Sexpr{np_mc5.accuracy.index}                    \\
Item 6                    & \Sexpr{np_mc6_time}                  & \Sexpr{np_mc6_omissions}                    & \Sexpr{np_mc6_falsepos}            & \Sexpr{np_mc6.accuracy.index}                    \\
Item 7                    & \Sexpr{np_mc7_time}                  & \Sexpr{np_mc7_omissions}                    & \Sexpr{np_mc7_falsepos}            & \Sexpr{np_mc7.accuracy.index}                    \\
Item 8                    & \Sexpr{np_mc8_time}                  & \Sexpr{np_mc8_omissions}                    & \Sexpr{np_mc8_falsepos}            & \Sexpr{np_mc8.accuracy.index}                    \\
\multicolumn{4}{r}{\textit{Automatized MC}}                                                      & \Sexpr{np_mc_auto_mc.accuracy.index}                    \\
\multicolumn{4}{r}{\textit{Non-Automatized MC}}                                                  & \Sexpr{np_mc_nonauto_mc.accuracy.index}                    \\
\multicolumn{2}{r}{\textit{Kaplan Raw Score}} & \Sexpr{np_mc_kaplan} & \textit{Kaplan Scaled Score} & \Sexpr{np_mc_kaplan_ss} \\ \hline

\rowcolor[HTML]{C0C0C0} 
\multicolumn{5}{c}{\cellcolor[HTML]{C0C0C0}\textbf{WMS-IV Symbol Span}}                                                     \\ \hline
\rowcolor[HTML]{C0C0C0} 
\multicolumn{3}{c}{\cellcolor[HTML]{C0C0C0}}                                  & Raw Score        & Scaled Score             \\
\multicolumn{3}{c}{Total Raw Score}                                           & \Sexpr{np_symbol}            & \Sexpr{np_symbol.scaled}                    \\
\multicolumn{3}{c}{\# Correct Trials}                                         & \Sexpr{np_symbol_trials}            & \cellcolor[HTML]{C0C0C0} \\ \hline

\end{tabular}
\end{table}

\clearpage

Notes: \Sexpr{np_notes}

\end{document}
